version: '3.5'
services:
  spring-app:
    container_name: spring-boot-docker
    image: cvillegas92/cvillegas-backend
    volumes:
      - spring:/data/spring
    ports:
      - "9191:9191"
    networks:
      - spring-cloud-network
    restart: unless-stopped
    build:
      context: cvillegas-backend
      dockerfile: Dockerfile

networks:
  spring-cloud-network:
    driver: bridge
  postgres:
    driver: bridge
volumes:
  spring:
  postgres:

