server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-type: PKCS12
    key-store-password: cvillegas-dev
    key-password: cvillegas-dev
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://cvillegas-dev.com:5432/cvillegas
    username: postgres
    password: a28d8896f9

user:
  data:
    domain: cvillegas-dev.com