server:
  port: 9292
  servlet:
    session:
      cookie.http-only: true
      timeout: 20m
    contextPath: /api/v1
### DATABASE CONFIGURATION
spring:
  application:
    name: cvg-backend
  mail:
    host: smtp.gmail.com
    port: 587
    username: cristianvg9692@gmail.com
    password: Pa28d8896f9123.1992
    properties:
      mail:
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
  profiles:
    active: @appProfile@
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  main:
    allow-circular-references: true
  config:
    use-legacy-processing: true

#Spring Session
  session:
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
      table-name: SPRING_SESSION
    store-type: jdbc
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB

# security
security:
  jwt:
    secret-key: secret
    expiration-time: 36000
    accessTokenCookieName: authToken

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.1.66:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

