server:
  port: 9191
    # https
  ssl:
    key-store: classpath:keystore.jks
    key-store-type: JKS
    key-store-password: cvillegas-dev
    key-password: cvillegas-dev
    key-alias: cvillegas-dev
### DATABASE CONFIGURATION
spring:
  profiles:
    active: @appProfile@
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-circular-references: true
  config:
    use-legacy-processing: true
logging:
  level:
    org.hibernate.SQL: debug

# security
jwt:
  secret: secret
  expiration: 36000
