server:
  port: 9191
### DATABASE CONFIGURATION
spring:
  profiles:
    active: @appProfile@
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-circular-references: true
  config:
    use-legacy-processing: true
logging:
  level:
    org.hibernate.SQL: debug

# security
jwt:
  secret: secret
  expiration: 36000
