server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-type: PKCS12
    key-store-password: cvillegas-dev
    key-password: cvillegas-dev
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://cvillegas-dev.com:5432/cvillegas
    username: postgres
    password: a28d8896f9
  mail:
    host: smtp.gmail.com
    port: 587
    username: cristianvg9692@gmail.com
    password: Pa28d8896f9123.1992
    properties:
      mail:
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp