server:
  port: 9191
  servlet:
    session:
      cookie.http-only: true
      timeout: 20m
### DATABASE CONFIGURATION
spring:
  profiles:
    active: @appProfile@
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  main:
    allow-circular-references: true
  config:
    use-legacy-processing: true

#Spring Session
  session:
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
      table-name: SPRING_SESSION
    store-type: jdbc
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB

logging:
  file:
    name: app.log
  #logging:
  #level:
    #org.hibernate.SQL: debug

# security
jwt:
  secret: secret
  expiration: 36000
  accessTokenCookieName: authToken




